name: Docker image build and push
on: [push]
jobs:
  Docker-Build_push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out respository code
      - uses: actions/checkout@v2
      - name: docker image build
      - run: docker build -t cqhaisenbao/web-test:lastest .
      - name: list docker image
      - run: docker image ls
